name: Test Suite

on:
  - pull_request

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Tox
      run: pip install tox
    - name: Run lint
      run: tox -e lint
  unit-and-func-tests:
    name: Unit, & Functional Tests
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10', '3.11']
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install Tox
      run: pip install tox
    - name: Run unit & functional tests
      run: tox -e unit,functional

  integration-test:
    name: Integration test with LXD
    runs-on: ubuntu-22.04
    timeout-minutes: 40
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: pip install tox
    - name: Setup operator environment
      uses: charmed-kubernetes/actions-operator@main
      with:
        provider: lxd
        juju-channel: 3.1/stable

    - name: Create Charmcraft lxc project
      run: lxc --project charmcraft project create local:charmcraft

    - name: Run integration tests
      run: tox -e integration
